### ISSUE TITLE
[feat] Notification Fragment에 존재하는 recycler view에 대해서 databinding 적용하기

### ISSUE THREAD

**Issue by boogi-woogi** [TEAM-DAME/Dame-Android#99]
## 화면 이름
Notification Fragment

## 기능 설명
하드코딩 되어있는 recylcerView를 BindingAdapter와 ViewModel을 이용해 구현하기

## 체크 리스트
- [x] NotifiactionViewModel 구현
- [x] BindingAdapter 구현
- [x] 하드 코딩 되어 string 들을 String resource로 분리 및 리팩토링

**Comment by onseok** [comment]
커밋 메시지 작성하실때 끝에 `(#99)` 이렇게 달아주시면 감사하겠습니당

**Comment by onseok** [comment]
커밋 메시지 작성하실때 끝에 `(#99)` 이렇게 달아주시면 감사하겠습니당

**Comment by boogi-woogi** [comment]
넵!!
